### PR TITLE
Add cross-compilation support for lib

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Add different kind of cross compilation targets to the CI.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Works, both failing tests are still related that rustfmt for nightly does not build since a couple of commits: https://rust-lang-nursery.github.io/rust-toolstate/

**Review by Klaven — APPROVED** [review]
looks good to me. it looks like rust nightly is building too.

**Comment by saschagrunert** [comment]
/assign @mrunalp 
The build failure should be gone as soon as the container image with the latest nightly got rebuild. Probably have to merge manually because of tide.

**Comment by mrunalp** [comment]
needs rebase

**Comment by saschagrunert** [comment]
> needs rebase

Yep, rebased :+1:

**Comment by saschagrunert** [comment]
@mrunalp PTAL

**Pull request merged**
